version: '3.4'

services:
  catalogdb:
    image: mongo
  
  mscatalog:
    image: ${DOCKER_REGISTRY-}mscatalog
    build:
      context: .
      dockerfile: MsCatalog/Dockerfile

  msbasket:
    image: ${DOCKER_REGISTRY-}msbasket
    build:
      context: .
      dockerfile: MsBasket/Dockerfile

volumes:
    mongo_data: 
